---
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: true

- name: Ensure Nginx is started & enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true